//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class blood_service
    {
        public int id { get; set; }
        public Nullable<int> blood { get; set; }
        public Nullable<int> service { get; set; }
        public Nullable<int> analyzator { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> finished { get; set; }
        public Nullable<double> rezult { get; set; }
    
        public virtual analyzator analyzator1 { get; set; }
        public virtual blood blood1 { get; set; }
        public virtual service service1 { get; set; }
    }
}
