//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class blood
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public blood()
        {
            this.blood_service = new HashSet<blood_service>();
        }
    
        public int id { get; set; }
        public Nullable<int> pacient { get; set; }
        public string barcode { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> code_probirki { get; set; }
    
        public virtual data_pacient data_pacient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blood_service> blood_service { get; set; }
    }
}
