//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class buhgalter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public buhgalter()
        {
            this.company_of_buh = new HashSet<company_of_buh>();
            this.service_bugh = new HashSet<service_bugh>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string patronymic { get; set; }
        public Nullable<System.DateTime> date_time_input { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> bithdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<company_of_buh> company_of_buh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service_bugh> service_bugh { get; set; }
    }
}
