//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class story_input
    {
        public int id { get; set; }
        public string login { get; set; }
        public Nullable<System.DateTime> last_input { get; set; }
        public string type_popitki { get; set; }
    }
}
